<?xml version="1.0"?>
<package format="3">
  <name>rs_gui</name>
  <version>0.0.1</version>
  <description>Teleoperation HUD — Qt5 + OpenGL</description>
  <maintainer email="you@email.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>msg_manual_teleop</depend>

  <build_depend>libqt5-opengl-dev</build_depend>
  <build_depend>qtbase5-dev</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
